### ISSUE TITLE
Registration-free WinRT is now available

### ISSUE THREAD

**Issue by Huios** [therealkenc/WinformsOutOfProcessWinRT#1]
@therealkenc I'm opening this in response to a closed issue you posted a while back: https://github.com/Microsoft/cppwinrt/issues/256

Calling Windows Runtime Components is now supported in the latest Windows release. More info here: 
https://blogs.windows.com/buildingapps/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/

Feel free to close this when you're done reading, I was just looking for a way to get in touch with you.

**Comment by therealkenc** [comment]
Wow; thanks for taking the time to do that🐱‍👤.

Backref [Microsoft/DesktopBridgeToUWP-Samples#52](https://github.com/Microsoft/DesktopBridgeToUWP-Samples/issues/52) (so I can find it again)
